# Generated by Django 4.2.4 on 2023-10-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppClub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("subtitulo", models.CharField(max_length=100)),
                ("fecha", models.DateField()),
                ("tema", models.CharField(max_length=100)),
                ("desarrollo", models.TextField(max_length=300)),
                ("imagen", models.ImageField(upload_to="noticias/")),
                ("pie_de_foto", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="evento",
            old_name="partido",
            new_name="deporte",
        ),
        migrations.RemoveField(
            model_name="deporte",
            name="fecha_fin",
        ),
        migrations.RemoveField(
            model_name="deporte",
            name="fecha_inicio",
        ),
    ]
