# Generated by Django 4.2.4 on 2023-09-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClub', '0002_alter_deporte_nombre_alter_evento_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='apellido',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
