# Generated by Django 4.2.4 on 2023-10-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppClub", "0002_noticia_rename_partido_evento_deporte_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deporte",
            name="categoria",
            field=models.CharField(default="categoria", max_length=60),
            preserve_default=False,
        ),
    ]
