# Generated by Django 4.2.4 on 2023-10-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppClub", "0003_deporte_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="avatares/"),
        ),
    ]
