# Generated by Django 4.2.4 on 2023-10-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClub', '0004_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(null=True, upload_to='noticias'),
        ),
    ]
