# Generated by Django 4.2.4 on 2023-09-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClub', '0004_evento_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='deportes',
            field=models.ManyToManyField(to='AppClub.deporte'),
        ),
    ]
