# Generated by Django 4.2.4 on 2023-09-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClub', '0005_socio_deportes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='descripcion',
            field=models.CharField(max_length=60),
        ),
    ]
