# Generated by Django 4.2.4 on 2023-10-11 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppClub", "0004_alter_noticia_imagen"),
        ("AppClub", "0005_alter_noticia_imagen"),
    ]

    operations = []
