# Generated by Django 4.2.4 on 2023-10-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppClub", "0007_alter_noticia_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacto",
            name="tipo_consulta",
            field=models.IntegerField(
                choices=[
                    [0, "Consulta"],
                    [1, "Reclamo"],
                    [2, "Sugerencia"],
                    [3, "Felicitaciones"],
                ]
            ),
        ),
    ]
