# Generated by Django 4.2.4 on 2023-10-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClub', '0008_alter_contacto_tipo_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
