# Generated by Django 4.2.4 on 2023-10-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClub', '0009_noticia_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='desarrollo',
            field=models.TextField(max_length=600),
        ),
    ]
