# Generated by Django 4.2.4 on 2023-10-14 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppClub", "0011_comentario"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comentario",
            options={"ordering": ["-fecha"]},
        ),
    ]
