# Generated by Django 4.2.4 on 2023-10-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_perfil_deporte_alter_perfil_evento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfil",
            name="apellido",
        ),
        migrations.RemoveField(
            model_name="perfil",
            name="nombre",
        ),
    ]
