# Generated by Django 4.2.4 on 2023-10-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppClub", "0008_alter_contacto_tipo_consulta"),
        ("authentication", "0003_remove_perfil_apellido_remove_perfil_nombre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfil",
            name="deporte",
        ),
        migrations.RemoveField(
            model_name="perfil",
            name="evento",
        ),
        migrations.AddField(
            model_name="perfil",
            name="deporte",
            field=models.ManyToManyField(blank=True, to="AppClub.deporte"),
        ),
        migrations.AddField(
            model_name="perfil",
            name="evento",
            field=models.ManyToManyField(blank=True, to="AppClub.evento"),
        ),
    ]
