# Generated by Django 4.2.4 on 2023-10-11 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppClub", "0008_alter_contacto_tipo_consulta"),
        ("authentication", "0004_remove_perfil_deporte_remove_perfil_evento_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfil",
            name="deporte",
        ),
        migrations.RemoveField(
            model_name="perfil",
            name="evento",
        ),
        migrations.AddField(
            model_name="perfil",
            name="deporte",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="AppClub.deporte",
            ),
        ),
        migrations.AddField(
            model_name="perfil",
            name="evento",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="AppClub.evento",
            ),
        ),
    ]
