# Generated by Django 4.2.4 on 2023-10-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_perfil_deporte_alter_perfil_evento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="fecha_nacimiento",
            field=models.DateField(
                blank=True,
                help_text="Por favor, ingrese la fecha de su cita en el formato DD/MM/AAAA.",
                null=True,
            ),
        ),
    ]
