# Generated by Django 4.2.4 on 2023-10-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_alter_perfil_fecha_nacimiento"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perfil",
            options={"verbose_name_plural": "Perfiles de Usuario"},
        ),
        migrations.AlterField(
            model_name="perfil",
            name="fecha_nacimiento",
            field=models.DateField(
                blank=True, help_text="Formato DD/MM/AAAA.", null=True
            ),
        ),
    ]
