# Generated by Django 4.2.4 on 2023-10-14 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_comentario"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comentario",
        ),
    ]
